name: Run API Tests with Allure and HTML Report
on:
  workflow_dispatch:
  
jobs:
  build:
    name: API Test Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true

      - name: Install NewMan and HTMLextra reporter plugins
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-allure

      - name: Create Test Results Folder
        run: mkdir -p GitHubAPITestResults

      - name: Get Current TimeStamp
        id: current_TimeStamp
        run: echo "current_TimeStamp=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Run the collection with Newman and HTMLextra
        env:
          GIT_TOKEN: ${{secrets.TOKEN_ACCESS}}
        run: |
          newman run "Postman Collections/github_api_testing.json" --env-var "gitUserToken=$GIT_TOKEN" --environment "Postman Collections/GitTest.postman_environment.json" -r htmlextra --reporter-htmlextra-browserTitle "GitHub API Report" --reporter-htmlextra-title "GITHUB API Testing DashBoard" --reporter-htmlextra-export GitHubAPITestResults/postman-newman-report.html --insecure --suppress-exit-code  
 

        

  
